name: CI
on:
  push:
    branches:
      - main
      - "jordandubu"
  [pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Use Node.js
        uses: action/setup-node@v3
      with:
        node-version: 16.14.0
